[package]
name = "reqs"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
http = "1.1.0"
http-body-util = "0.1.2"
hyper = { version = "1.3.1", features = ["client"] }
mime = "0.3.17"
serde = "1.0.203"
serde_json = "1.0.118"
serde_urlencoded = "0.7.1"
